# Variables
@baseUrl = http://localhost:3000
@feature = auth
@id = 61343bf1fd69b0002fed3cee

### @name localhost
GET {{baseUrl}}

### @name register
POST {{baseUrl}}/api/{{feature}}/register
Content-Type: application/json

{
    "username": "ntdat104",
    "password": "abc123123",
    "name": "Tien Dat"
}

### @name login
POST {{baseUrl}}/api/{{feature}}/login
Content-Type: application/json

{
    "username": "ntdat104",
    "password": "abc123123"
}

###
GET {{baseUrl}}/api/post
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTY0M2MyMDZjMDZmYjkwZmE4ZDk3OGIiLCJuYW1lIjoiVGllbiBEYXQiLCJpYXQiOjE2MzM5NTkzNTYsImV4cCI6MTYzMzk1OTM4Nn0.yYENtkr8zO0baMW3cW2TiqLv2ATjVwCltcImWKGpuoL89kaYncUgm6AslXghxp3DhHuLojiqEdKK_c0OOndIEg

###
GET {{baseUrl}}/api/{{feature}}/token
Refreshtoken: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTY0M2MyMDZjMDZmYjkwZmE4ZDk3OGIiLCJuYW1lIjoiVGllbiBEYXQiLCJpYXQiOjE2MzM5NTkyNTksImV4cCI6MTY2NTUxNjg1OX0.H1KdN43YErWugtPgmRwDO7gVxINXpj-mBUMezS2DVs_u3OGG-9_HPtpZkCYMFqPzmHfCzMmBMjBKGE0RXOPfsQ
