# Variables
@baseUrl = http://localhost:3000
@feature = auth
@id = 61343bf1fd69b0002fed3cee

### @name localhost
GET {{baseUrl}}

### @name register
POST {{baseUrl}}/api/{{feature}}/register
Content-Type: application/json

{
    "username": "ntdat104",
    "password": "abc123123",
    "name": "Tien Dat"
}

### @name login
POST {{baseUrl}}/api/{{feature}}/login
Content-Type: application/json

{
    "username": "ntdat104",
    "password": "abc123123"
}

###
GET {{baseUrl}}/api/post
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTY0M2MyMDZjMDZmYjkwZmE4ZDk3OGIiLCJuYW1lIjoiVGllbiBEYXQiLCJpYXQiOjE2MzQ1NDM4NDEsImV4cCI6MTYzNDU0Mzg3MX0.-Rijgc_s431DRQhOV2zUcuGfBPgdbe6nX6sRVEoZVM5oc6uJMdm_L_ARqo2FYCSviLUh8pQaubW1_KmArK-snA

###
GET {{baseUrl}}/api/{{feature}}/token
Refreshtoken: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTY0M2MyMDZjMDZmYjkwZmE4ZDk3OGIiLCJuYW1lIjoiVGllbiBEYXQiLCJpYXQiOjE2MzQ1NDU2NzIsImV4cCI6MTYzNDU0NTY4Mn0.Rzmx6VqXFX0ULhBY1MwvoP9vS2PBv6wP_gWWb_mvlU0slT8g709qDALsNPUW6cXTSo3CgECrUO282k4TSFPIDQ
