# Variables
@baseUrl = http://localhost:3000
@feature = auth
@id = 61343bf1fd69b0002fed3cee

### @name localhost
GET {{baseUrl}}

### @name register
POST {{baseUrl}}/api/{{feature}}/register
Content-Type: application/json

{
    "username": "ntdat104111",
    "password": "abc123123123",
    "name": "Tien Dat"
}

### @name login
POST {{baseUrl}}/api/{{feature}}/login
Content-Type: application/json

{
    "username": "ntdat104111",
    "password": "abc123123123"
}

###
GET {{baseUrl}}/api/{{feature}}/token
RefreshToken: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTVmMjUzNDM2NWYxZWMwZmY2ZWI2OTciLCJpYXQiOjE2MzM2MjU0MjcsImV4cCI6MTY2NTE4MzAyN30.RYQtdZX_zl2FnM-bpuCQMd4gbg-Q8wdwXRl7cKY3e_KgQITZ3WpKUe1142twl2fwwCGNVNOLB3hJ5A7SpmvGWw

###
GET {{baseUrl}}/api/post
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTVmMjUzNDM2NWYxZWMwZmY2ZWI2OTciLCJpYXQiOjE2MzM2MjU0ODksImV4cCI6MTYzMzYyNTUwNH0.CNfrgIS008Ia_4R4B_sojMWLU5Sz3riB9hAOe_E2E2w4BQPW--JCVaP0HTJqNSdbI-rRsfRrgNK4oXBLpU-YKg